<Project Sdk="Microsoft.NET.Sdk">
  <!-- Inherits from root Directory.Build.props -->
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Ehm93.VS.Crops.Blight</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common\common.csproj" />
  </ItemGroup>
</Project>
